default_stages: [pre-commit]

repos:
  - repo: local
    hooks:

      - id: test
        name: Test hoom
        types: [post-checkout]
        pass_filenames: false
        language: script
        entry: post-checkout.sh
        verbose: true
