default_stages: [post-checkout]

repos:
  - repo: local
    hooks:

      # pre-commit

      - id: test
        name: Test hoom
        types: [post-checkout]
        pass_filenames: false
        language: script
        entry: post-checkout.sh
        verbose: true
